apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: photo
data:
  config.yaml: |
    s3:
      bucket_name: "vutest-0"
      region_name: "auto"
      public_url: "https://pub-4de729d2405d450d9f448d5c900b31b2.r2.dev"
    oidc:
      client_id: "photo-backend"
      server_metadata_url: "http://keycloak.keycloack.svc.cluster.local:80/realms/photo-realm/.well-known/openid-configuration"


      
    jwt:
      algorithm: "HS256"
      access_token_expire_minutes: 30
    frontend:
      url: "http://photo.test"

